# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_safe_dates}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kylejginavan"]
  s.date = %q{2012-02-24}
  s.description = %q{Uses Chronic to parse incoming dates and does not raise errors on invalid multi parameter settings.}
  s.email = %q{kylejginavan@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "has_safe_dates.gemspec",
    "has_safe_dates.gemspec.txt",
    "lib/has_safe_dates.rb",
    "lib/has_safe_dates/core_ext.rb",
    "spec/db/database.yml",
    "spec/db/schema.rb",
    "spec/has_safe_dates_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kylejginavan/has_safe_dates}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{The easy way to add safe dates to any Rails model.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency("activerecord", ['>= 3.1.0'])
      s.add_development_dependency("chronic")
      s.add_development_dependency("rspec", [">= 0"])
      s.add_development_dependency("rdoc", ["~> 3.12"])
      s.add_development_dependency("bundler", ["~> 1.0.0"])
      s.add_development_dependency("jeweler", ["~> 1.8.3"])
      s.add_development_dependency("simplecov", [">= 0"])
      s.add_development_dependency("sqlite3")
      s.add_development_dependency("rspec")
      s.add_development_dependency('database_cleaner')
  else
      s.add_dependency("activerecord", ['>= 3.1.0'])
      s.add_dependency("chronic")
      s.add_dependency("rspec", [">= 0"])
      s.add_dependency("rdoc", ["~> 3.12"])
      s.add_dependency("bundler", ["~> 1.0.0"])
      s.add_dependency("jeweler", ["~> 1.8.3"])
      s.add_dependency("simplecov", [">= 0"])
    end
  else
    s.add_dependency('activerecord', ['>= 3.1.0'])
    s.add_dependency('chronic')
    s.add_dependency("rspec", [">= 0"])
    s.add_dependency("rdoc", ["~> 3.12"])
    s.add_dependency("bundler", ["~> 1.0.0"])
    s.add_dependency("jeweler", ["~> 1.8.3"])
    s.add_dependency("simplecov", [">= 0"])
  end
end

